### ISSUE TITLE
http://chicagofilmmakers.org/dev/calendar #2

### ISSUE THREAD

**Issue by juliefab** [robandjulie/cwbugs#1]
warning block:
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 38 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 43 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 38 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 43 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 38 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 43 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 38 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 43 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 38 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 43 of /home/chifilmm/public_html/dev/sites/all/modules/calendar/theme/theme.inc).

**Comment by bitsandbooks** [comment]
Need source code access (See #2).

**Comment by bitsandbooks** [comment]
Drupal updated to 7.34; bug still appearing.

**Comment by bitsandbooks** [comment]
Calendar module updated to 7.x-3.5; appears to fix issue. Closing bug.
