### ISSUE TITLE
Fiscal Sponsorship projects Video bug

### ISSUE THREAD

**Issue by juliefab** [robandjulie/cwbugs#13]
http://chicagofilmmakers.org/dev/chicago-digital-media-production-fund/past-recipients

**Comment by bitsandbooks** [comment]
When you first load the Current Projects or Completed Projects pages, the video breaks the layout.

**Comment by bitsandbooks** [comment]
Reloading the page corrects it. (Why?)

**Comment by bitsandbooks** [comment]
Only seems to happen when returning to the page from administrative UI.
