### ISSUE TITLE
This shouldn't lead to the front page it should lead to the Instructor static page.

### ISSUE THREAD

**Issue by juliefab** [robandjulie/cwbugs#6]
![Issue screenshot](https://trackducks.s3.amazonaws.com/crop/54d24f1ecfb07a2d4c0b96c7-1423240731417-238-389)
- Browser: Firefox 35
- OS: Mac OS
- Screen: 1400 x 942

[More details](https://app.trackduck.com/#/project/54d24f1ecfb07a2d4c0b96c7/issue/54d4edf089f28c5b5d2d1c3f)

**Comment by bitsandbooks** [comment]
closed by Julie
